Repository pypa/packaging, pull requests merged in 2020-04, with the labels that each got.

#285 Add major, minor and macro properties to doc
  docs/version.rst
Labels: documentation, packaging.version

#292 Add NewType for normalized names
  .pre-commit-config.yaml
  CHANGELOG.rst
  packaging/_compat.py
  packaging/_typing.py
  packaging/markers.py
  packaging/requirements.py
  packaging/specifiers.py
  packaging/tags.py
  packaging/utils.py
  packaging/version.py
Labels: enhancement

#297 Document version classes comparison behaviour
  docs/version.rst
Labels: documentation
